# Generated by Django 6.0.7 on 2026-09-24 04:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='bakery.bakery')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('production_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='bakery.bakery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='production.product')),
            ],
            options={
                'ordering': ['-production_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('bakery', 'name'), name='unique_product_name_per_bakery'),
        ),
        migrations.AddConstraint(
            model_name='productionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='production_quantity_positive'),
        ),
    ]
