# Generated by Django 6.0.7 on 2026-09-30 16:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
        ('production', '0002_align_with_deliverable1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price_at_sale', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='bakery.bakery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='production.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_timestamp'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_sold__gt', 0)), name='sales_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price_at_sale__gte', 0)), name='sales_unit_price_non_negative'), models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sales_total_non_negative')],
            },
        ),
    ]
