# Generated by Django 6.0.7 on 2026-08-09 18:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('unit_type', models.CharField(choices=[('mass', 'Mass'), ('volume', 'Volume'), ('count', 'Count')], max_length=10)),
            ],
            options={
                'verbose_name': 'unit of measure',
                'verbose_name_plural': 'units of measure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='bakery.bakery')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='inventory.unitofmeasure')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('bakery', 'name'), name='unique_ingredient_name_per_bakery'), models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='ingredient_quantity_non_negative')],
            },
        ),
    ]
