# Generated by Django 6.0.7 on 2026-08-10 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
        ('inventory', '0002_seed_units_of_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('movement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('StockIn', 'Stock-In (Purchase)'), ('Consumption', 'Consumption'), ('Correction', 'Correction'), ('Loss', 'Loss')], default='StockIn', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.bakery')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient')),
            ],
        ),
    ]
