# Generated by Django 5.2.16 on 2026-08-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_units_of_measure'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.CheckConstraint(condition=models.Q(('abbreviation__in', ('kg', 'g', 'u', 'L'))), name='unit_abbreviation_is_supported'),
        ),
    ]
