# Generated by Django 5.2.16 on 2026-08-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement'),
        ('inventory', '0003_unitofmeasure_unit_abbreviation_is_supported'),
    ]

    operations = [
    ]
