# Generated by Django 6.1 on 2026-08-31 17:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_merge_20260810_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_stock_threshold', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_configuration', to='inventory.ingredient')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('minimum_stock_threshold__gt', 0)), name='alert_minimum_stock_threshold_positive')],
            },
        ),
    ]
