# Generated by Django 6.0.7 on 2026-08-31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alertconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfiguration',
            name='minimum_stock_threshold',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.01')),
                ],
            ),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='expiration_warning_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='alertconfiguration',
            name='alert_minimum_stock_threshold_positive',
        ),
        migrations.AddConstraint(
            model_name='alertconfiguration',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(('minimum_stock_threshold__isnull', True))
                    | models.Q(('minimum_stock_threshold__gt', 0))
                ),
                name='alert_minimum_stock_threshold_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='alertconfiguration',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(('expiration_warning_days__isnull', True))
                    | models.Q(('expiration_warning_days__gte', 0))
                ),
                name='alert_expiration_warning_days_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='alertconfiguration',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(('minimum_stock_threshold__isnull', False))
                    | models.Q(('expiration_warning_days__isnull', False))
                ),
                name='alert_at_least_one_threshold_configured',
            ),
        ),
    ]
